### ISSUE TITLE
why reshape 4*10*1

### ISSUE THREAD

**Issue by caijiangyao1991** [CEfanmin/JDD#1]
source_data_array = np.log1p(np.array(source_data)).reshape(90993,4,10,1)
不是很明白为什么CNN要reshape 成4*10*1，那如果我的特征数是352，我要reshape成4*88*1吗，请问是怎么跟图像的卷积联系起来呢？

**Comment by CEfanmin** [comment]
每一个用户的特征是一个tensor [4,10,1]

**Comment by CEfanmin** [comment]
> source_data_array = np.log1p(np.array(source_data)).reshape(90993,4,10,1)
> 不是很明白为什么CNN要reshape 成4_10_1，那如果我的特征数是352，我要reshape成4_88_1吗，请问是怎么跟图像的卷积联系起来呢？
每一个用户是一个tensor[4,10,1]
